### ISSUE TITLE
Because the Internet Screenplay

### ISSUE THREAD

**Issue by joshuaj1397** [BurntOstrich/burntostrich.github.io#1]
Hey, can you send me the BTI Screenplay that used to be hosted on your page? Along with all of the necessary files? It's my all-time favourite album and I think you were the only one that preserved it's original format from becausetheinter.net so I want to preserve it myself and keep it so I can show my kids one day haha.

**Comment by PenguinxEnjoi** [comment]
I also would wish for this to happen.

**Comment by BurntOstrich** [comment]
Go for that clone/download B) @joshuaj1397 @PenguinxEnjoi

**Comment by PenguinxEnjoi** [comment]
@BurntOstrich it won't let us do that though bc I think you deleted everything?? Unless your reuploades

**Comment by PenguinxEnjoi** [comment]
Ohh shoot thank you based god

**Comment by joshuaj1397** [comment]
@BurntOstrich Done and done thanks a lot man!
